parser: babel-eslint
extends:
  - airbnb
  - prettier
  - prettier/react
rules:
  react/jsx-filename-extension: off
  import/no-extraneous-dependencies: off
  jsx-a11y/anchor-is-valid: off
  import/prefer-default-export: off
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - single
  max-len:
    - error
    - 80
