baseURL = "/"
languageCode = "en-us"
title = "Sam Atkins"
# googleAnalytics = "XXX"

# Code Blocks
pygmentsCodeFences = true
pygmentsStyle = "monokai"


[Privacy]

[Privacy.disqus]
  disable = true

[Privacy.googleAnalytics]
  anonymizeIP = true
  respectDoNotTrack = true
  useSessionStorage = false

[Author]
  name = "Sam Atkins"
  profile = "https://github.com/cubiio"

[Taxonomies]
  tag = "tags"

[Params]
  intro = true
  headline = "Sam Atkins"
  description = "Father. Husband. Software Engineer."
  github = "https://github.com/cubiio"
  linkedin = "https://www.linkedin.com/in/atkinssam/"
  twitter = "https://twitter.com/dev__sam"
  opengraph = true
  shareTwitter = true
  shareFacebook = true
  shareGooglePlus = true
  shareLinkedIn = true
  dateFormat = "2006 Jan 2"

[Permalinks]
  post = "/post/:filename/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 2
