[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
from = "https://samatkinsme.netlify.com/*"
to = "https://www.samatkins.me/:splat"
status = 301

[[redirects]]
from = "/becoming-a-pro-web-dev"
to = "/post/becoming-a-pro-web-dev"
status = 301
force = true

[[redirects]]
from = "/blogging-again"
to = "/post/blogging-again"
status = 301
force = true

[[redirects]]
from = "/building-map-project"
to = "/post/building-map-project"
status = 301
force = true

[[redirects]]
from = "/building-map-project"
to = "/post/building-map-project"
status = 301
force = true

[[redirects]]
from = "/converting-react-app-typescript"
to = "/post/converting-react-app-typescript"
status = 301
force = true

[[redirects]]
from = "/installing-tree"
to = "/post/installing-tree"
status = 301
force = true

[[redirects]]
from = "/python-project-virtualenv"
to = "/post/python-project-virtualenv"
status = 301
force = true

[[redirects]]
from = "/setting-up-eslint-and-prettier"
to = "/post/setting-up-eslint-and-prettier"
status = 301
force = true

[[redirects]]
from = "/sublime-text-python"
to = "/post/sublime-text-python"
status = 301
force = true

[[redirects]]
from = "/udacity-react-nanodegree-reflections"
to = "/post/udacity-react-nanodegree-reflections"
status = 301
force = true

[[redirects]]
from = "/why-hugo"
to = "/post/why-hugo"
status = 301
force = true

[[redirects]]
from = "/100daysofcode"
to = "/post/100daysofcode"
status = 301
force = true

[[redirects]]
from = "/100-days-of-coding-challenge-summary"
to = "/post/100-days-of-coding-challenge-summary"
status = 301
force = true
