[context.production]
command = "hugo -b $DEPLOY_PRIME_URL"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.48"

[context.branch-deploy]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
publish = "public"

[context.branch-deploy.environment]
HUGO_VERSION = "0.48"

[context.deploy-preview]
command = "hugo --buildFuture"
publish = "public"

[context.deploy-preview.environment]
HUGO_VERSION = "0.48"

[[redirects]]
from = "https://samatkinsme.netlify.com/*"
to = "https://www.samatkins.me/:splat"
status = 301
